document.writeln("<footer id=\'footer\'> <a class=\'go-top\' href=\'#\' title=\'Go Top\'>TOP</a>");
document.writeln("    <div class=\'inner-wrap\'>");
document.writeln("        <h2 class=\'footer-logo\'><img src=\'../tem/tw/images/footer-logo.png\' width=\'165\' height=\'46\' alt=\'捷克仕移動\' /></h2>");
document.writeln("        <div class=\'addr\'>");
document.writeln("            <h3>捷克仕移動</h3>");
document.writeln("            <address>");
document.writeln("            <ul>");
document.writeln("                <li class=\'icon-location\'>新北市土城區金城路三段16號5樓</li>");
document.writeln("                <li class=\'icon-tel\'>0919799534</li>");
document.writeln("                <!--<li class=\'icon-fax\'>(02)1234-5678</li>-->");
document.writeln("                <li class=\'icon-mail\'><a href=\'mailto:lily@gex.com.tw\'>lily@gex.com.tw</a></li>");
document.writeln("            </ul>");
document.writeln("            </address>");
document.writeln("						<div class=\'contact-info\'>");
document.writeln("						<h3>業務窗口 <strong>Lily</strong></h3>");
document.writeln("						<ul>");
document.writeln("							<li class=\'icon-tel\'>0919799534</li>");
document.writeln("							<!--<li class=\'icon-sky\'><div id=\'SkypeButton\'></div></li>-->");
document.writeln("						</ul>");
document.writeln("						</div>");
document.writeln("        </div>");
document.writeln("        <nav id=\'footer-nav\' class=\'footer-nav\'>");
document.writeln("            <ul>");
document.writeln("                <li> ");
document.writeln("                    <a href=\'../company.html\' title=\'關於公司\'>關於公司</a> ");
document.writeln("                    <a href=\'../service.html\' title=\'服務項目\'>服務項目</a> ");
document.writeln("                    <a href=\'../viewpoint.html\' title=\'顧問觀點\'>顧問觀點</a>");
document.writeln("                    <a href=\'../case.html\' title=\'成功案例\'>成功案例</a> ");
document.writeln("                    <a href=\'../contact.html\' title=\'聯絡我們\'>聯絡我們</a>");
document.writeln("                </li>");
document.writeln("                <li></li>");
document.writeln("            </ul>");
document.writeln("        </nav>");
document.writeln("        <div class=\'copyright\'>");
document.writeln("            <p>Copyright © 捷克仕移動 All rights reserved.</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("		</footer>");