document.writeln("<header id=\'header\'>");
document.writeln("<div class=\'inner-wrap\'>");
document.writeln("        <h1 id=\'logo\'> <a href=\'index.html\' title=\'捷克仕移動\'> <img src=\'tem/tw/images/logo.png\' width=\'181\' height=\'50\' alt=\'捷克仕移動\' /> </a> </h1>");
document.writeln("        <a id=\'nav-btn\' class=\'icon-thumb\' href=\'#main-nav\' title=\'選單鈕\'> <span class=\'thumb thumb-1\'></span> <span class=\'thumb thumb-2\'></span> <span class=\'thumb thumb-3\'></span> </a> ");
document.writeln("        <!-- 主選單[li當前單元加上樣式class:on] START -->");
document.writeln("        <nav id=\'main-nav\'>");
document.writeln("            <ul>");
document.writeln("                <li > <a href=\'company.html\' title=\'關於捷克仕\'>關於捷克仕</a> </li>");
document.writeln("                <li > <a href=\'service.html\' title=\'服務項目\'>服務項目</a> </li>");
document.writeln("                <li ><a href=\'viewpoint.html\' title=\'顧問觀點\'>顧問觀點</a></li>");
document.writeln("                <li ><a href=\'news.html\' title=\'最新消息\'>最新消息</a></li>");
document.writeln("                <li ><a href=\'faq.html\' title=\'常見問題\'>常見問題</a></li>");
document.writeln("                <li ><a href=\'case.html\' title=\'成功案例\'>成功案例</a></li>");
document.writeln("                <li class=\'last\'><a href=\'contact.html\' title=\'聯絡我們\'>聯絡我們</a></li>");
document.writeln("            </ul>");
document.writeln("        </nav>");
document.writeln("        <!-- 主選單 END --> ");
document.writeln("    </div>");
document.writeln("    <div class=\'sub-nav-bg\'></div>");
document.writeln("    <!-- 次選單背景 --> ");
document.writeln("    </header>");